#ifndef UNIFROG_MEDIA_TUNING_DEFAULTS_H
#define UNIFROG_MEDIA_TUNING_DEFAULTS_H

#include <unifrog_default_options.h>

#define UNIFROG_MEDIA_TUNING_DEFAULT_INITIALIZER { \
   UNIFROG_DEFAULT_MEDIA_VIDEO_FEED_LEAD_MS, \
   UNIFROG_DEFAULT_MEDIA_AUDIO_FEED_LEAD_MS, \
   UNIFROG_DEFAULT_MEDIA_VIDEO_KSHM_SIZE, \
   UNIFROG_DEFAULT_MEDIA_VIDEO_LOWRES_KSHM_SIZE, \
   UNIFROG_DEFAULT_MEDIA_FILE_BUFFER_SIZE, \
   UNIFROG_DEFAULT_MEDIA_FILE_BUFFER_MIN_SIZE, \
   UNIFROG_DEFAULT_MEDIA_FILE_READAHEAD_SIZE, \
   UNIFROG_DEFAULT_MEDIA_FILE_READAHEAD_MIN_SIZE, \
   UNIFROG_DEFAULT_MEDIA_FILE_READAHEAD_SLOTS, \
   UNIFROG_DEFAULT_MEDIA_VIDEO_READAHEAD_SIZE, \
   UNIFROG_DEFAULT_MEDIA_VIDEO_READAHEAD_MIN_SIZE, \
   UNIFROG_DEFAULT_MEDIA_VIDEO_READAHEAD_SLOTS, \
   UNIFROG_DEFAULT_MEDIA_VIDEO_PREFILL_TARGET_MS, \
   UNIFROG_DEFAULT_MEDIA_VIDEO_PREFILL_MIN_BYTES, \
   UNIFROG_DEFAULT_MEDIA_VIDEO_PREFILL_MAX_BYTES, \
   UNIFROG_DEFAULT_MEDIA_VIDEO_PRELOAD_MAX_BYTES, \
   UNIFROG_DEFAULT_MEDIA_AUDIO_MAX_HW_AHEAD_MS, \
   UNIFROG_DEFAULT_MEDIA_VIDEO_MAX_HW_AHEAD_MS, \
   UNIFROG_DEFAULT_MEDIA_SEEK_WARMUP_PACKETS, \
   UNIFROG_DEFAULT_MEDIA_SEEK_VIDEO_WARMUP_PACKETS, \
   UNIFROG_DEFAULT_MEDIA_SEEK_VIDEO_RECOVER_WARMUP_PACKETS, \
   UNIFROG_DEFAULT_MEDIA_HW_AHEAD_MAX_WAIT_MS, \
   UNIFROG_DEFAULT_MEDIA_SEEK_SETTLE_MS, \
   UNIFROG_DEFAULT_MEDIA_SEEK_ACCELERATE_FRAMES, \
   UNIFROG_DEFAULT_MEDIA_SEEK_KEYFRAME_DROP_LIMIT, \
   UNIFROG_DEFAULT_MEDIA_SEEK_PREROLL_DECODE_MS, \
   UNIFROG_DEFAULT_MEDIA_SEEK_PREROLL_HD_DECODE_MS, \
   UNIFROG_DEFAULT_MEDIA_SEEK_PREROLL_KEYFRAME_MAX_BYTES, \
   UNIFROG_DEFAULT_MEDIA_VIDEO_STUCK_BEHIND_MS, \
   UNIFROG_DEFAULT_MEDIA_VIDEO_STALL_RECOVER_MS, \
   UNIFROG_DEFAULT_MEDIA_VIDEO_RECOVER_GAP_MS, \
   UNIFROG_DEFAULT_MEDIA_VIDEO_WRITE_RECOVER_MAX, \
   UNIFROG_DEFAULT_MEDIA_VIDEO_WRITE_EPERM_RECOVER_MS, \
   UNIFROG_DEFAULT_MEDIA_FILE_SLOW_READ_LOG_MS, \
   UNIFROG_DEFAULT_MEDIA_AUDIO_BUFFERING_START_MS, \
   UNIFROG_DEFAULT_MEDIA_AUDIO_BUFFERING_END_MS, \
   UNIFROG_DEFAULT_MEDIA_VIDEO_BUFFERING_START_MS, \
   UNIFROG_DEFAULT_MEDIA_VIDEO_BUFFERING_END_MS, \
   UNIFROG_DEFAULT_MEDIA_RESET_VIDDEC_ON_FAIL, \
   UNIFROG_DEFAULT_MEDIA_GB300_AUDDEC_PROBE_ONCE \
}

#endif
