# Central option inventory used by Makefile checks and generated examples.

UNIFROG_DEFAULT_AUDIO := 1
UNIFROG_DEFAULT_CPU := 702
UNIFROG_DEFAULT_FRAMESKIP := 1
UNIFROG_DEFAULT_DISPLAY := 0
UNIFROG_DEFAULT_FRAMEBUFFER := 0
UNIFROG_DEFAULT_GAIN := 1
UNIFROG_DEFAULT_GE_CLOCK := -1
UNIFROG_DEFAULT_BACKLIGHT := -1
UNIFROG_DEFAULT_KEYMAP := 0
UNIFROG_DEFAULT_STATE_SLOT := 0
UNIFROG_DEFAULT_STATE_AUTO_LOAD := 0
UNIFROG_DEFAULT_STATE_AUTO_SAVE := 0
UNIFROG_DEFAULT_SORT_DESC := 0
UNIFROG_DEFAULT_SHOW_HIDDEN := 0
UNIFROG_DEFAULT_FOLDER_COUNTS := 0
UNIFROG_DEFAULT_MIXED_CONTENT := 1
UNIFROG_DEFAULT_DISPLAY_EMPTY_FOLDER := 1
UNIFROG_DEFAULT_MENU_COUNTER_FOLDER := 1
UNIFROG_DEFAULT_MENU_COUNTER_FILE := 1
UNIFROG_DEFAULT_CONTENT_COLLECT := 1
UNIFROG_DEFAULT_CONTENT_HISTORY := 1
UNIFROG_DEFAULT_CLOCK_ENABLED := 0
UNIFROG_DEFAULT_TITLE_INCLUDE_ROOT := 0
UNIFROG_DEFAULT_THEME_ALTERNATE := 0
UNIFROG_DEFAULT_BOXART_HIDDEN := 1
UNIFROG_DEFAULT_LAUNCH_SPLASH := 1
UNIFROG_DEFAULT_SOUND_ENABLED := 0
UNIFROG_DEFAULT_LOG_FLUSH_EVERY := $(if $(filter 0,$(LOG_FLUSH_EVERY)),0,1)
UNIFROG_DEFAULT_LANGUAGE := 0
UNIFROG_DEFAULT_LANGUAGE_NAME := english
UNIFROG_DEFAULT_THEME_NAME := muos
UNIFROG_DEFAULT_STORAGE_PROFILE := boot
UNIFROG_DEFAULT_ROM_ROOT := /ROMS
UNIFROG_DEFAULT_ROM_ROOTS := /ROMS
UNIFROG_DEFAULT_ROM_ROOT_LABEL := ROMs
UNIFROG_DEFAULT_ROM_SYSTEM := gba:gpsp

RUNTIME_SETTING_KEYS := \
	audio cpu frameskip display framebuffer gain ge_clock backlight keymap \
	state_slot state_auto_load state_auto_save sort_desc show_hidden \
	folder_counts mixed_content display_empty_folder menu_counter_folder \
	menu_counter_file content_collect content_history clock_enabled \
	title_include_root theme_alternate boxart_hidden launch_splash \
	sound_enabled log_flush_every language language_name theme_name \
	storage_profile rom_root rom_roots rom_root_label rom_system \
	last_path last_core

RUNTIME_SETTINGS_LINES := \
	'\# UniFrog runtime settings example.' \
	'\# Edit /unifrog_data/settings.ini on the SD card to override these.' \
	'' \
	'\# Libretro launch defaults. Keep framebuffer=0 for RGB565 on SF2000.' \
	'audio=$(UNIFROG_DEFAULT_AUDIO)' \
	'cpu=$(UNIFROG_DEFAULT_CPU)' \
	'frameskip=$(UNIFROG_DEFAULT_FRAMESKIP)' \
	'display=$(UNIFROG_DEFAULT_DISPLAY)' \
	'framebuffer=$(UNIFROG_DEFAULT_FRAMEBUFFER)' \
	'gain=$(UNIFROG_DEFAULT_GAIN)' \
	'ge_clock=$(UNIFROG_DEFAULT_GE_CLOCK)' \
	'backlight=$(UNIFROG_DEFAULT_BACKLIGHT)' \
	'keymap=$(UNIFROG_DEFAULT_KEYMAP)' \
	'state_slot=$(UNIFROG_DEFAULT_STATE_SLOT)' \
	'state_auto_load=$(UNIFROG_DEFAULT_STATE_AUTO_LOAD)' \
	'state_auto_save=$(UNIFROG_DEFAULT_STATE_AUTO_SAVE)' \
	'' \
	'\# Browser and menu behavior.' \
	'sort_desc=$(UNIFROG_DEFAULT_SORT_DESC)' \
	'show_hidden=$(UNIFROG_DEFAULT_SHOW_HIDDEN)' \
	'folder_counts=$(UNIFROG_DEFAULT_FOLDER_COUNTS)' \
	'mixed_content=$(UNIFROG_DEFAULT_MIXED_CONTENT)' \
	'display_empty_folder=$(UNIFROG_DEFAULT_DISPLAY_EMPTY_FOLDER)' \
	'menu_counter_folder=$(UNIFROG_DEFAULT_MENU_COUNTER_FOLDER)' \
	'menu_counter_file=$(UNIFROG_DEFAULT_MENU_COUNTER_FILE)' \
	'content_collect=$(UNIFROG_DEFAULT_CONTENT_COLLECT)' \
	'content_history=$(UNIFROG_DEFAULT_CONTENT_HISTORY)' \
	'clock_enabled=$(UNIFROG_DEFAULT_CLOCK_ENABLED)' \
	'title_include_root=$(UNIFROG_DEFAULT_TITLE_INCLUDE_ROOT)' \
	'theme_alternate=$(UNIFROG_DEFAULT_THEME_ALTERNATE)' \
	'boxart_hidden=$(UNIFROG_DEFAULT_BOXART_HIDDEN)' \
	'launch_splash=$(UNIFROG_DEFAULT_LAUNCH_SPLASH)' \
	'sound_enabled=$(UNIFROG_DEFAULT_SOUND_ENABLED)' \
	'log_flush_every=$(UNIFROG_DEFAULT_LOG_FLUSH_EVERY)' \
	'' \
	'\# Theme, language, storage, and ROM roots.' \
	'language=$(UNIFROG_DEFAULT_LANGUAGE)' \
	'language_name=$(UNIFROG_DEFAULT_LANGUAGE_NAME)' \
	'theme_name=$(UNIFROG_DEFAULT_THEME_NAME)' \
	'storage_profile=$(UNIFROG_DEFAULT_STORAGE_PROFILE)' \
	'rom_root=$(UNIFROG_DEFAULT_ROM_ROOT)' \
	'rom_roots=$(UNIFROG_DEFAULT_ROM_ROOTS)' \
	'rom_root_label=$(UNIFROG_DEFAULT_ROM_ROOT_LABEL)' \
	'rom_system=$(UNIFROG_DEFAULT_ROM_SYSTEM)' \
	'last_path=' \
	'last_core='

CONFIG_EXAMPLE_LINES := \
	'\# UniFrog local build options example.' \
	'\# Copy selected lines into untracked config.mk when needed.' \
	'' \
	'TOOLCHAIN ?= $(TOOLCHAIN)' \
	'SDK ?= $(SDK)' \
	'DEPS ?= $(DEPS)' \
	'UNIFROG_DEPS_REPO_URL ?= $(UNIFROG_DEPS_REPO_URL)' \
	'DEP_SOURCE ?= $(DEP_SOURCE)' \
	'DEP_CHECKOUT ?= $(DEP_CHECKOUT)' \
	'DEP_DEPTH ?= $(DEP_DEPTH)' \
	'CORE_IDS ?= $(CORE_IDS)' \
	'' \
	'SD_MODE ?= $(SD_MODE)' \
	'SD_READ_MODE ?= $(SD_READ_MODE)' \
	'HCRTOS_MEDIA ?= $(HCRTOS_MEDIA)' \
	'FRONTEND_IMPL ?= $(FRONTEND_IMPL)' \
	'LOG_AUTO_FLUSH_BYTES ?= $(LOG_AUTO_FLUSH_BYTES)' \
	'LOG_FLUSH_EVERY ?= $(LOG_FLUSH_EVERY)' \
	'LOG_DISK_WRITES ?= $(LOG_DISK_WRITES)' \
	'' \
	'MEDIA_AUDIO_FEED_LEAD_MS ?= $(MEDIA_AUDIO_FEED_LEAD_MS)' \
	'MEDIA_VIDEO_FEED_LEAD_MS ?= $(MEDIA_VIDEO_FEED_LEAD_MS)' \
	'MEDIA_VIDEO_KSHM_SIZE ?= $(MEDIA_VIDEO_KSHM_SIZE)' \
	'MEDIA_VIDEO_LOWRES_KSHM_SIZE ?= $(MEDIA_VIDEO_LOWRES_KSHM_SIZE)' \
	'MEDIA_FILE_BUFFER_SIZE ?= $(MEDIA_FILE_BUFFER_SIZE)' \
	'MEDIA_FILE_READAHEAD_SIZE ?= $(MEDIA_FILE_READAHEAD_SIZE)' \
	'MEDIA_VIDEO_READAHEAD_SIZE ?= $(MEDIA_VIDEO_READAHEAD_SIZE)' \
	'MEDIA_VIDEO_READAHEAD_SLOTS ?= $(MEDIA_VIDEO_READAHEAD_SLOTS)' \
	'MEDIA_VIDEO_PRELOAD_MAX_BYTES ?= $(MEDIA_VIDEO_PRELOAD_MAX_BYTES)' \
	'MEDIA_HW_AHEAD_MAX_WAIT_MS ?= $(MEDIA_HW_AHEAD_MAX_WAIT_MS)' \
	'MEDIA_SEEK_ACCELERATE_FRAMES ?= $(MEDIA_SEEK_ACCELERATE_FRAMES)'

DEFAULT_OPTIONS_HEADER_LINES := \
	'\#ifndef UNIFROG_DEFAULT_OPTIONS_H' \
	'\#define UNIFROG_DEFAULT_OPTIONS_H' \
	'' \
	'\#define UNIFROG_DEFAULT_AUDIO $(UNIFROG_DEFAULT_AUDIO)' \
	'\#define UNIFROG_DEFAULT_CPU $(UNIFROG_DEFAULT_CPU)' \
	'\#define UNIFROG_DEFAULT_FRAMESKIP $(UNIFROG_DEFAULT_FRAMESKIP)' \
	'\#define UNIFROG_DEFAULT_DISPLAY $(UNIFROG_DEFAULT_DISPLAY)' \
	'\#define UNIFROG_DEFAULT_FRAMEBUFFER $(UNIFROG_DEFAULT_FRAMEBUFFER)' \
	'\#define UNIFROG_DEFAULT_GAIN $(UNIFROG_DEFAULT_GAIN)' \
	'\#define UNIFROG_DEFAULT_GE_CLOCK $(UNIFROG_DEFAULT_GE_CLOCK)' \
	'\#define UNIFROG_DEFAULT_BACKLIGHT $(UNIFROG_DEFAULT_BACKLIGHT)' \
	'\#define UNIFROG_DEFAULT_KEYMAP $(UNIFROG_DEFAULT_KEYMAP)' \
	'\#define UNIFROG_DEFAULT_STATE_SLOT $(UNIFROG_DEFAULT_STATE_SLOT)' \
	'\#define UNIFROG_DEFAULT_STATE_AUTO_LOAD $(UNIFROG_DEFAULT_STATE_AUTO_LOAD)' \
	'\#define UNIFROG_DEFAULT_STATE_AUTO_SAVE $(UNIFROG_DEFAULT_STATE_AUTO_SAVE)' \
	'\#define UNIFROG_DEFAULT_SORT_DESC $(UNIFROG_DEFAULT_SORT_DESC)' \
	'\#define UNIFROG_DEFAULT_SHOW_HIDDEN $(UNIFROG_DEFAULT_SHOW_HIDDEN)' \
	'\#define UNIFROG_DEFAULT_FOLDER_COUNTS $(UNIFROG_DEFAULT_FOLDER_COUNTS)' \
	'\#define UNIFROG_DEFAULT_MIXED_CONTENT $(UNIFROG_DEFAULT_MIXED_CONTENT)' \
	'\#define UNIFROG_DEFAULT_DISPLAY_EMPTY_FOLDER $(UNIFROG_DEFAULT_DISPLAY_EMPTY_FOLDER)' \
	'\#define UNIFROG_DEFAULT_MENU_COUNTER_FOLDER $(UNIFROG_DEFAULT_MENU_COUNTER_FOLDER)' \
	'\#define UNIFROG_DEFAULT_MENU_COUNTER_FILE $(UNIFROG_DEFAULT_MENU_COUNTER_FILE)' \
	'\#define UNIFROG_DEFAULT_CONTENT_COLLECT $(UNIFROG_DEFAULT_CONTENT_COLLECT)' \
	'\#define UNIFROG_DEFAULT_CONTENT_HISTORY $(UNIFROG_DEFAULT_CONTENT_HISTORY)' \
	'\#define UNIFROG_DEFAULT_CLOCK_ENABLED $(UNIFROG_DEFAULT_CLOCK_ENABLED)' \
	'\#define UNIFROG_DEFAULT_TITLE_INCLUDE_ROOT $(UNIFROG_DEFAULT_TITLE_INCLUDE_ROOT)' \
	'\#define UNIFROG_DEFAULT_THEME_ALTERNATE $(UNIFROG_DEFAULT_THEME_ALTERNATE)' \
	'\#define UNIFROG_DEFAULT_BOXART_HIDDEN $(UNIFROG_DEFAULT_BOXART_HIDDEN)' \
	'\#define UNIFROG_DEFAULT_LAUNCH_SPLASH $(UNIFROG_DEFAULT_LAUNCH_SPLASH)' \
	'\#define UNIFROG_DEFAULT_SOUND_ENABLED $(UNIFROG_DEFAULT_SOUND_ENABLED)' \
	'\#define UNIFROG_DEFAULT_LOG_FLUSH_EVERY $(UNIFROG_DEFAULT_LOG_FLUSH_EVERY)' \
	'\#define UNIFROG_DEFAULT_LANGUAGE $(UNIFROG_DEFAULT_LANGUAGE)' \
	'\#define UNIFROG_DEFAULT_LANGUAGE_NAME "$(UNIFROG_DEFAULT_LANGUAGE_NAME)"' \
	'\#define UNIFROG_DEFAULT_THEME_NAME "$(UNIFROG_DEFAULT_THEME_NAME)"' \
	'\#define UNIFROG_DEFAULT_STORAGE_PROFILE "$(UNIFROG_DEFAULT_STORAGE_PROFILE)"' \
	'\#define UNIFROG_DEFAULT_ROM_ROOT "$(UNIFROG_DEFAULT_ROM_ROOT)"' \
	'\#define UNIFROG_DEFAULT_ROM_ROOT_LABEL "$(UNIFROG_DEFAULT_ROM_ROOT_LABEL)"' \
	'' \
	'\#endif'
